name: Executar Script Python via Make

on:
  repository_dispatch:
    types: [disparar_via_make]
  workflow_dispatch: # 👈 ADICIONE ESTA LINHA EXATAMENTE AQUI

jobs:
  rodar-script:
    runs-on: ubuntu-latest

    steps:
    - name: Baixar o código do Git
      uses: actions/checkout@v4

    - name: Configurar o Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'

    - name: Instalar dependências
      run: |
        pip install -r requirements.txt

    - name: Executar o arquivo Python
      run: python codigo_original.py

    - name: Salvar Relatório Gerado
      uses: actions/upload-artifact@v4
      with:
        name: Relatorio-PandaPe
        path: Relatorio_Final_PandaPe.csv
